-- Seed Knowledge Resources
DELETE FROM public.knowledge_resources;

INSERT INTO public.knowledge_resources (title, description, resource_type, category, source_name, source_url, document_url, state, scope, language, is_verified, page_count, duration) VALUES
(
  'ICAR Kharif Agro-Advisories for Farmers',
  'Farmer-oriented seasonal agricultural advisories covering crop and farming practices for the Kharif season.',
  'PDF',
  'Best Practices',
  'ICAR',
  'https://icar.gov.in/',
  'https://icar.gov.in/sites/default/files/2024-05/Kharif-Advisory-2024.pdf',
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  45,
  NULL
),
(
  'Soil Health Card Information & Guidelines',
  'Official information about soil health parameters, nutrient status and soil-based recommendations provided by the Government of India.',
  'GOVERNMENT_DOCUMENT',
  'Soil Management',
  'Government of India',
  'https://soilhealth.dac.gov.in/',
  'https://soilhealth.dac.gov.in/public/images/SHC_Guidelines.pdf',
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  20,
  NULL
),
(
  'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
  'Official information about PM-KISAN, eligibility, registration, and beneficiary services.',
  'WEBSITE',
  'Government Schemes',
  'Government of India',
  'https://pmkisan.gov.in/',
  NULL,
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  NULL,
  NULL
),
(
  'Pradhan Mantri Fasal Bima Yojana (PMFBY) Guidelines',
  'Official crop insurance scheme guidelines and farmer information for financial support during crop loss/damage.',
  'PDF',
  'Government Schemes',
  'Ministry of Agriculture & Farmers Welfare',
  'https://pmfby.gov.in/',
  'https://pmfby.gov.in/pdf/Revised_Operational_Guidelines.pdf',
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  82,
  NULL
),
(
  'Drip Irrigation for Water Saving',
  'Precision water delivery techniques to save water and increase yield. A comprehensive guide by ICAR.',
  'GUIDE',
  'Irrigation',
  'ICAR',
  'https://icar.gov.in/',
  NULL,
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  NULL,
  NULL
),
(
  'Maharashtra Agriculture Department - Official Portal',
  'State-specific schemes, advisories, and resources for farmers in Maharashtra.',
  'WEBSITE',
  'Government Schemes',
  'State Agriculture Department',
  'https://krishi.maharashtra.gov.in/',
  NULL,
  'Maharashtra',
  'STATE',
  'Marathi',
  true,
  NULL,
  NULL
),
(
  'Madhya Pradesh Krishi Net',
  'Official portal for farmers in Madhya Pradesh providing scheme details, market prices, and advisories.',
  'WEBSITE',
  'Government Schemes',
  'State Agriculture Department',
  'https://mpkrishi.mp.gov.in/',
  NULL,
  'Madhya Pradesh',
  'STATE',
  'Hindi',
  true,
  NULL,
  NULL
),
(
  'Handbook of Agriculture',
  'Comprehensive agricultural reference covering major areas of Indian agriculture. Published by ICAR.',
  'RESEARCH_PUBLICATION',
  'Crop Guides',
  'ICAR',
  'https://icar.gov.in/en/all-publications',
  NULL,
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  NULL,
  NULL
),
(
  'Organic Farming Best Practices',
  'Detailed guide on organic farming methods, certification process, and benefits.',
  'ARTICLE',
  'Organic Farming',
  'National Centre of Organic Farming',
  'https://ncof.dacnet.nic.in/',
  NULL,
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  NULL,
  NULL
),
(
  'Integrated Pest Management (IPM) Strategies',
  'Learn how to manage crop pests effectively using biological and environmentally safe methods.',
  'VIDEO',
  'Pest Management',
  'Krishi Vigyan Kendra',
  'https://www.youtube.com/watch?v=placeholder-ipm-video',
  NULL,
  'PAN_INDIA',
  'PAN_INDIA',
  'English',
  true,
  NULL,
  '12:45'
);
